### ISSUE TITLE
Backend API to add product be id throws an error if an attempt is made to add the same product by id again.

### ISSUE THREAD

**Issue by ananddeb23** [TechUniv2018/ShopSocial#20]
Suggestion: Promise needs to be caught.
Please close the issue if something has been overlooked by me in making the calls.

**Comment by maheshhp** [comment]
I acknowledge this issue. I have fixed the query by making it and upsert. Changes will be pushed in the next commit

**Comment by maheshhp** [comment]
Successfully resolved
