### ISSUE TITLE
Create an API for user registration

### ISSUE THREAD

**Issue by sahilbalodi** [TechUniv2018/ShopSocial#21]
What is required?
An API for the users to register themselves which will create a unique entry for the user in our user-details relation.

What should be implemented?
A route /user/registration , accepting a POST request has to be implemented which takes User name , password and email id and make corresponding entry for the user on the user-Details table.

What does the timeline look like?
We aim to achieve the implementation by 19th Feb 2018.

**Comment by theSuiGenerisAakash** [comment]
Had a bug with response codes. Fixed in #27 .
