### ISSUE TITLE
Create migration and models for Admin table

### ISSUE THREAD

**Issue by sahilbalodi** [TechUniv2018/ShopSocial#29]
What do we want?
The model for Admin table required for our database where we are going to store all Admin-related data.

How do we do it?
With reference to the ER diagram prepared before, we need to create the schema followed by migrations and models using Sequelize so that our app server communicates with the DB using the ORM.

How does the timeline look like?
The migrations can be completed by 22nd Feb 2018.

**Comment by theSuiGenerisAakash** [comment]
#31
