### ISSUE TITLE
Create route and handler for admin login

### ISSUE THREAD

**Issue by sahilbalodi** [TechUniv2018/ShopSocial#33]
**What is required?**
An route for admin to login to his account so that the admin can  add or remove products from the website.

**What should be implemented?**
- A route /admin/login , accepting a POST request has to be implem
What should be implemented?
- A route /admin/login , accepting a POST request has to be implemented which takes admin's email-id and password and checks the credentials from the admin-details table and authenticate the admin .

**What does the timeline look like?**
We aim to achieve the implementation by 26th Feb 2018.

**Comment by theSuiGenerisAakash** [comment]
#34

**Comment by theSuiGenerisAakash** [comment]
Done. Hopefully.
