### ISSUE TITLE
Handler and route for user login

### ISSUE THREAD

**Issue by sahilbalodi** [TechUniv2018/ShopSocial#39]
**What is required?**

A route for handling the user login request from the frontend

**What should be implemented?**

A route /user/login , accepting a POST request has to be implemented which takes user's email-id and password and checks the credentials from the user-details table and authenticate the user.

**Timeline:**

We aim to achieve the implementation by 5th Mar 2018.

**Comment by theSuiGenerisAakash** [comment]
#41
