### ISSUE TITLE
Inital setup: How To Do - React integration with backend

### ISSUE THREAD

**Issue by theSuiGenerisAakash** [TechUniv2018/ShopSocial#9]
**What do we need?**
A clear concept of how React components would be handled and rendered with data from app server say when a request is made by the client for a webpage.

**How do we do it?**
Consult people who know it and read!

**What does the timeline look like?**
We intend to have this done by 16th Feb, 2018.

**Comment by theSuiGenerisAakash** [comment]
This is clear, right? 

@TechUniv2018/team-5 Use `window.fetch`.

**Comment by ananddeb23** [comment]
Yes!

**Comment by theSuiGenerisAakash** [comment]
Good then. All the best!

P.S. We still can learn how to pick up React files from the React app and place them on the backend server from where they could be served.
